10
1
world
21
39
6
18
World
world
38
20
11
19
World
@@
@@
42
    ,GRRRRRR!
name,MARGO! 
job ,I am cursed
curs,A witch cast a spell on me
spel,She turned me into a beast
beas,Now I hide away
witc,The hag Quoxonia!
hag ,The witch!
quox,But she said I changed myself
chan,But she did it, I know
myse,But she did it, I know
rune,In one of my caverns
bye ,Beware the Witch
@@,@@
0
