11
0
world
21
36
16
12
World
@@
PE 44 01
IN 44 64 100
MV 100 01 64
MS Take the x-ray spell
..
@@
61
    ,Yes Sir
name,Joms
job ,I'm the butler
butl,Of my master
mast,An old mage
mage,He is now retired
reti,Ask the master
bye ,Yes Sir
@@,@@
44
    ,Welcome wizard
name,I am the great Ramog
job ,I'm a retired mage
reti,I have lossed my magic
loss,It just went one day
magi,I know a usefull spell
spel,*01The X-ray spell
bye ,Use magic wisely
@@,@@
0
